apiVersion: v1
kind: Secret
metadata:
  name: addres-book-app-secret
  namespace: default
type: Opaque
stringData:
  databaseScheme: postgres
  databaseUser: postgres
  databasePassword: test
  databasePort: 5432
  databaseHost: address-book-postgres