apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-book-app
  labels:
    app: address-book
spec:
  replicas: 3
  selector:
    matchLabels:
      app: address-book
  template:
    metadata:
      labels:
        app: address-book
    spec:
      containers:
      - name: address-book-app
        image: alexlowe64/addressbook:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_SCHEMA
          valueFrom:
            secretKeyRef:
              name: address-book-app-secret
              key: databaseScheme

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: address-book-app-secret
              key: databaseUser

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: address-book-app-secret
              key: databasePassword

        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: address-book-app-secret
              key: databasePort

        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: address-book-app-secret
              key: databaseHost